<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Shacara</name>
   <tag></tag>
   <elementGuidId>2b579905-4756-41d6-b02d-fd68c737d3ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::h3[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>2930cb0b-89df-452f-b6b3-ac561a01c4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>37c23b7d-46f1-42f0-a099-37b6dcb7ffbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shacara</value>
      <webElementGuid>757a0815-9ef0-494a-bdc3-ef185dd84871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;topheader navbar-fixed-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;rows&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 remove-pad&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;navbar-header&quot;]/a[@class=&quot;visible-lg visible-md&quot;]/h3[@class=&quot;logo&quot;]</value>
      <webElementGuid>900051e7-0d0a-4832-95c5-7e7c37bbca7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::h3[1]</value>
      <webElementGuid>114c2005-ef62-49a1-aac0-be5668b74cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/preceding::h3[1]</value>
      <webElementGuid>c91c1aff-a59b-4f18-9499-12ecd3210b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::h3[2]</value>
      <webElementGuid>ff8a003c-07a3-476c-bc18-d265f35f3c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shacara']/parent::*</value>
      <webElementGuid>1c59f81d-766a-4bfb-b461-c494b505a516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>d6dac484-f6f8-4745-a770-5223d9a1a6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Shacara' or . = 'Shacara')]</value>
      <webElementGuid>d5a04984-a95c-469d-8740-7610a1344acc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
