<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Website</name>
   <tag></tag>
   <elementGuidId>af69645e-aa2c-4593-9cb7-7f8335369f5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.font-weight-bold.pix-nav-link.text-body-default.nav-link.pix-waiting.pix-animate.fade-in.animated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-29278']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ca6e7b1-8b3e-4bda-9142-b5115e185a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>a1ba1b7e-337a-438f-ad75-ea78de38d316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-bold pix-nav-link text-body-default nav-link pix-waiting pix-animate fade-in animated</value>
      <webElementGuid>db758c8b-9511-4d99-8ff9-7372400d257a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>626c2af7-be8b-4f51-ac99-1efd82091462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://brandcurb.com/en/services/website-design-development/</value>
      <webElementGuid>e541dfdc-86d3-4654-b5ff-1c18b0f6f530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-anim-type</name>
      <type>Main</type>
      <value>fade-in</value>
      <webElementGuid>f80ae861-eb7a-4e81-814a-8fb3e23cd0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>e9a1cbd7-4e32-4fc8-8264-c8d14250a4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-29278&quot;)/a[@class=&quot;font-weight-bold pix-nav-link text-body-default nav-link pix-waiting pix-animate fade-in animated&quot;]</value>
      <webElementGuid>f5a0cb9b-b104-4dc4-b4cf-e36a7076ed8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-29278']/a</value>
      <webElementGuid>5cc703be-9b26-47b9-a928-9d9b7f5a86d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow us on'])[1]/following::a[6]</value>
      <webElementGuid>ad3dd55d-af8e-4b3a-b6e8-4bc26dda4424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Marketing Packages for Non-Profit Organizations'])[1]/following::a[6]</value>
      <webElementGuid>d58b66c3-42f1-4822-b980-14cf7a0a9992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEO'])[1]/preceding::a[1]</value>
      <webElementGuid>46b16592-2058-4cc0-96d4-03bbf621a176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://brandcurb.com/en/services/website-design-development/')]</value>
      <webElementGuid>a6ed8054-8d56-4d2d-be63-e3c447efde3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>14d6c4c5-d040-47f5-8c52-8c1d89ec2dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Website' and @href = 'https://brandcurb.com/en/services/website-design-development/' and (text() = 'Website' or . = 'Website')]</value>
      <webElementGuid>bee361ac-f2e1-44f8-9438-23f96f387430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
