<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_Choose your locationChoose your location</name>
   <tag></tag>
   <elementGuidId>26a96c6d-42f1-4cac-b8ce-8842bd7a4b32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>header.a-popover-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a-popover-1']/div/header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>5fe90b6a-b28c-4d93-9cc3-1b5d57d9a845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-popover-header</value>
      <webElementGuid>ed9094b3-ed77-48db-89cd-f1e9921a676d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose your locationChoose your location</value>
      <webElementGuid>3391738f-ac05-48a0-8600-e1d565c0e6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-popover-1&quot;)/div[@class=&quot;a-popover-wrapper&quot;]/header[@class=&quot;a-popover-header&quot;]</value>
      <webElementGuid>231ce591-faef-49f0-9598-c9106dce2ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-1']/div/header</value>
      <webElementGuid>5ef66081-efc8-4ba5-84a2-3a230ca13b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to top'])[2]/following::header[1]</value>
      <webElementGuid>168aa797-575f-4d5d-bf60-3ac2a4a11fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[3]/following::header[1]</value>
      <webElementGuid>05979a1f-d22b-4db1-92e4-69bea4fd1a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feature requested to not be shown'])[1]/preceding::header[1]</value>
      <webElementGuid>a8dbc016-e487-488e-ac75-edb6f4fb98a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/header</value>
      <webElementGuid>4f5fb7e8-45a4-4fe3-966e-84d5b1ca89f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[(text() = 'Choose your locationChoose your location' or . = 'Choose your locationChoose your location')]</value>
      <webElementGuid>90c20c2d-b4a8-4899-8000-4d22f02a9200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
