<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Learn More_AppLandingPage</name>
   <tag></tag>
   <elementGuidId>17cae183-3727-4c46-bba3-c0232ac48a62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AppLandingPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='AppLandingPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>853ef686-e3f4-49f8-af2b-0a9d6aece804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AppLandingPage</value>
      <webElementGuid>35319b16-2b4b-4f61-84d9-8962351c9d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>AppLandingPage</value>
      <webElementGuid>a90e5302-8612-4540-adcf-bd06f9d13c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/%7b638343270290000220%7d/webresources/msdyn_appmanagementcontrol</value>
      <webElementGuid>c45c7050-0e76-4d43-b198-29394f2f035f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-aw pa-cj pa-cb </value>
      <webElementGuid>1de027c5-0558-4221-8fc2-48e1bde500a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AppLandingPage&quot;)</value>
      <webElementGuid>cc5d2906-b1e9-4400-9334-bb900a1dc2d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='AppLandingPage']</value>
      <webElementGuid>1a7e4433-405b-4d25-b7f4-8664b0c4c9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panels']/div/div/iframe</value>
      <webElementGuid>fbca7eb6-db9b-4ced-8bfa-d6c7082eeab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b1348818-9d3c-405a-885c-1d3f9e32e51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'AppLandingPage' and @title = 'AppLandingPage' and @src = '/%7b638343270290000220%7d/webresources/msdyn_appmanagementcontrol']</value>
      <webElementGuid>74dc9310-5d6f-404d-b0fd-ce356c520890</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
