<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_conduit</name>
   <tag></tag>
   <elementGuidId>97abccf1-1913-4d0c-a932-4e83344c9179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.logo-font.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Feed'])[1]/preceding::h1[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>1d5e60fb-e03d-4da8-8c8f-3570be587426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-font ng-binding</value>
      <webElementGuid>c636fd58-4461-462f-b7e3-7152d342e2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>::$ctrl.appName | lowercase</value>
      <webElementGuid>912609fc-13b9-40cb-af34-cdbc9e30f60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>conduit</value>
      <webElementGuid>5fcc3342-bf97-45c1-8772-703c3ad53729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;home-page ng-scope&quot;]/div[@class=&quot;banner&quot;]/div[@class=&quot;container&quot;]/h1[@class=&quot;logo-font ng-binding&quot;]</value>
      <webElementGuid>6c6cd7e0-8e4b-48f4-9dee-69141b6ce917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Feed'])[1]/preceding::h1[1]</value>
      <webElementGuid>e8bccedb-7adc-4c72-ad90-04faff8b7c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Global Feed'])[1]/preceding::h1[1]</value>
      <webElementGuid>569bd835-4126-4bfa-8cb8-28b33d373a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>cd345e14-e40f-44b1-9eaa-58673edc4e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'conduit' or . = 'conduit')]</value>
      <webElementGuid>d736d544-2724-490b-8d24-5cc38a9ad9fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
