<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>9e1fe609-ecea-44f5-be40-c0e5a8820aaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/nav/div/div/div[2]/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea9844ef-dbe9-4823-9cf2-9d539c84f646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://accounts.lambdatest.com/login?_gl=1*ifj2jk*_gcl_au*NjUyOTY5NDIxLjE2OTg5MDk4NjQ.</value>
      <webElementGuid>aa1dd0fd-a75b-4539-8ad3-0d87aedb84be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop:block desktop:mt-10 nav-link inline-block py-8 mr-30 desktop:mr-0 text-size-16 font-medium text-ltBlack-50 desktop:text-center desktop:py-10 desktop:rounded rounded login</value>
      <webElementGuid>0bda039b-6624-4fec-9220-b750c24ec1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>299aa475-a384-45c0-9d1e-a60ecf8ba59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;container&quot;]/div[@class=&quot;px-2 desktop:py-15&quot;]/div[@class=&quot;flex -mx-2 items-center desktop:block&quot;]/div[@class=&quot;header__menu px-2 desktop:w-full&quot;]/div[@class=&quot;desktop:mt-10 desktop:text-left desktop:hidden&quot;]/div[@class=&quot;flex items-center desktop:block&quot;]/div[@class=&quot;w-5/12 md:text-right desktop:text-left desktop:w-full desktop:px-15 relative flex desktop:block items-center justify-end&quot;]/a[@class=&quot;desktop:block desktop:mt-10 nav-link inline-block py-8 mr-30 desktop:mr-0 text-size-16 font-medium text-ltBlack-50 desktop:text-center desktop:py-10 desktop:rounded rounded login&quot;]</value>
      <webElementGuid>c96a018f-1c5f-457c-9622-1eba4149b80b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/nav/div/div/div[2]/div/div/div[2]/a</value>
      <webElementGuid>993c1846-3678-4697-afde-23a59ef1b104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>855eef2b-a300-488c-81fd-53fa7e64147f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[1]</value>
      <webElementGuid>80eb8b0a-7ea4-4520-8cc7-aca0a95ed1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Testing Advisor'])[1]/following::a[2]</value>
      <webElementGuid>da7b67ef-9c53-46f8-b91a-271146e60657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a Demo'])[1]/preceding::a[1]</value>
      <webElementGuid>3081fe68-d39c-4dfe-8466-1f28a98f9b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>232ad1f5-6fc1-40d1-a472-3b9472fca06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://accounts.lambdatest.com/login?_gl=1*ifj2jk*_gcl_au*NjUyOTY5NDIxLjE2OTg5MDk4NjQ.')]</value>
      <webElementGuid>af1e266c-261e-4614-a111-97dc87c849d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>cdd9ba4c-931f-4157-8e2c-fc787ee20b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://accounts.lambdatest.com/login?_gl=1*ifj2jk*_gcl_au*NjUyOTY5NDIxLjE2OTg5MDk4NjQ.' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>7f13bec0-4da1-4a9b-9033-0cf9ce7376cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
