<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Home</name>
   <tag></tag>
   <elementGuidId>297a96c7-b691-48ae-9e01-fee656a37ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sitemap-entity-Home_8E2112DC-AD90-40F5-BEBE-0A8D80785D75']/div/div/div[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>10dd8716-b541-4092-8a37-0b434ffa8d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-ei pa-p pa-ew pa-ex pa-ey pa-ez pa-an pa-bd pa-bc </value>
      <webElementGuid>f8d94e52-c8e0-427a-97c1-67b711b490c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>c73d5626-8f62-426e-852b-6a5063304003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sitemap-entity-Home_8E2112DC-AD90-40F5-BEBE-0A8D80785D75&quot;)/div[@class=&quot;pa-a pa-bl pa-dv pa-dw pa-dq pa-x pa-dx pa-dy pa-dz pa-ea pa-eb pa-ec pa-ed pa-ee flexbox&quot;]/div[@class=&quot;pa-a pa-ef pa-eg pa-x pa-f pa-p pa-bd pa-eh flexbox&quot;]/div[@class=&quot;pa-ct pa-e pa-p pa-es flexbox&quot;]/span[@class=&quot;pa-ei pa-p pa-ew pa-ex pa-ey pa-ez pa-an pa-bd pa-bc&quot;]</value>
      <webElementGuid>e88a42bf-2624-40d7-a520-f11b2cb089d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sitemap-entity-Home_8E2112DC-AD90-40F5-BEBE-0A8D80785D75']/div/div/div[2]/span[2]</value>
      <webElementGuid>41817449-8bae-4523-a130-cd0e81b11ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign out'])[1]/following::span[5]</value>
      <webElementGuid>77a4d619-828c-4776-b1e1-4a8e99a5e4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review and manage your work or school account information'])[1]/following::span[5]</value>
      <webElementGuid>0b6954c6-882e-48e5-b487-d9494f54c12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent'])[1]/preceding::span[3]</value>
      <webElementGuid>89860b54-e629-42ec-858b-1c3ca3cda3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pinned'])[1]/preceding::span[8]</value>
      <webElementGuid>6e6beb18-0844-450b-aa3b-8879555634af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>f6f14039-13c8-4ae9-849f-d279b2ec55b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>a73a979d-b39c-4b8f-adff-332a0cc009bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>cf70ea4a-c7fc-48a9-9637-d764f691bae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
